# --- Run & Path Settings ---
project_name: "2048-ppo-final"
run_name: "refactor-test"
output_dir: "data/" # Base directory for models and studies

# --- Resume Settings ---
load_model: false
checkpoint_path: null # e.g., "data/models/NewArch_SnakeReward_300M_Run/rl_model_100000000_steps.zip"

# --- Training Parameters ---
total_timesteps: 5_000_000
n_envs: 16
save_interval: 500_000

# --- PPO Hyperparameters---
ppo_params:
  n_steps: 2048
  gamma: 0.98
  ent_coef: 1.5e-5
  learning_rate:
    type: "linear_decay"
    initial_value: 0.0005
  clip_range: 0.2
  batch_size: 512
  n_epochs: 4

# --- Agent Architecture ---
features_dim: 256