# s--- Run & Path Settings ---
project_name: "2048-ppo-training"
run_name: "hybrid_ppo_v1_testing_before_sweep"
output_dir: "data" # Base directory for models and studies

# --- Resume Settings ---
load_model: false
checkpoint_path: null # e.g., "data/models/NewArch_SnakeReward_300M_Run/rl_model_100000000_steps.zip"

# --- Training Parameters ---
total_timesteps: 20_000_000
n_envs: 32
save_interval: 100_000

# --- PPO Hyperparameters---
ppo_params:
  n_steps: 512
  gamma: 0.9500241783796721
  ent_coef: 0.000006683561172757891
  learning_rate:
    type: "linear_decay"
    initial_value: 0.0002506795165161916
  clip_range: 0.2
  batch_size: 2048
  n_epochs: 4

# --- Agent Architecture ---
features_dim: 256
